version: 2

jobs:
  build:
    working_directory: ~/coin-admin
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
      - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
      - run:
        name: Install dependencies
        command: npm install
      - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run:
        name: Linting
        command: npm run lint
      - run:
        name: Testing
        command: npm run test
      - run:
        name: Building
        command: npm run build
      - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - dist

  deploy:
    working_directory: ~/coin-admin
    docker:
      - image: circleci/node:latest
    steps:
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
    - restore_cache:
      key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only:
              - master
