version: 2

jobs:
    build:
        working_directory: ~/coin-admin
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Building
                command: npm run build-prod
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
    deploy:
        working_directory: ~/coin-admin
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - run: 
                name: Adding know hosts
                command: mkdir -p ~/.ssh && ssh-keyscan -p 26421 leishi.zapto.org >> ~/.ssh/known_hosts
            - run:
                name: Transfer files
                command: scp -P 26421 -i ~/.ssh/id_rsa -prq ~/coin-admin/dist/* circleci@leishi.zapto.org:~/coin-admin

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
